### PR TITLE
Coveralls Unit Test Code Coverage

### LINKED ISSUE #622: Introduce Coveralls for continuous code coverage reporting
https://coveralls.io/

Ok ok ok so what will this give us? Function by function (and more) reporting on if test coverage  movement per pr!  This is powerful because we can say "Oh hai, test coverage went down, add tests or yo pr isn't welcome here".  As unique contributors increase it could be a nice helper to ensure product quality over time (high test coverage). 

It is free for open source :trollface: 

### [Here is some sample coverage reporting](https://coveralls.io/builds/13153485)
screen shot 2017-09-13 at 11 00 46 am

Thoughts @jeff-phillips-18 @dtaylor113 @cdcabrera ?

### PR DESCRIPTION
**Pull request by dtaylor113**
## Description
Implementation of the [grunt-karma-coveralls](https://github.com/mattjmorrison/grunt-karma-coveralls) plug-in.

Fixes #622

I'm now seeing results :-)
https://coveralls.io/github/patternfly/angular-patternfly

### CODE REVIEW

**Comment by cdcabrera** [comment]
Looking good so far @dtaylor113 

Are there any other package.json unit test dependencies we could bring up to date alongside this update, or should we try a separate PR?

**Comment by dtaylor113** [comment]
I vote for keeping them separate, just so we don't confuse the intention/goal of this PR.

**Comment by dtaylor113** [comment]
Closing the re-opening to force a build

**Comment by dtaylor113** [comment]
I believe this PR is ready to merge.

**Comment by dtaylor113** [comment]
Hi @jeff-phillips-18 can we review this PR and hopefully get it merged so I can verify Coveralls works with Travis for patternfly/angular-patternfly (not just my dtaylor113 fork)  -thanks

**Pull request merged**
