### PR TITLE
Bump ui-bootstrap version to 2.3.x and fix accordion groups

### PR DESCRIPTION
**Pull request by dgutride**
Updates ui-bootstrap version, all unit tests pass, linter passes and click through of test page found one issue with the accordion.  This addresses that as well based on the ui-bootstrap update.

@jeff-phillips-18 @dtaylor113

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
LGTM. Do we need the changes to fixed accordion in master as well? I noticed it is broken on the docs site as well.

**Comment by dgutride** [comment]
@jeff-phillips-18  - it's possible, I looked at the angular-patternfly hosted at patternfly.org and it seemed fine but I didn't check out the docs so they could be out of sync.

**Comment by dtaylor113** [comment]
Cloning this branch now to test.....

**Comment by dtaylor113** [comment]
Really, really, really small nit, but I am seeing it on my system.  When I launch the About modal, the close 'X' seems to be selected and highlighted:

image

When I do it from a-pf github pages:  https://www.patternfly.org/angular-patternfly/#/api/patternfly.modals.directive:pfAboutModal

It is not highlighted:

image

**Comment by dtaylor113** [comment]
I think I saw this when testing one of Jeff's earlier PRs, but couldn't reproduce it.  Just came across it again in testing this PR.   In ngdocs, when I select **pfNotificationDrawer**, I see a bunch of errors in the console:
```diff
- Error: <rect> attribute x: Expected length, "NaN".
- Error: <rect> attribute y: Expected length, "NaN".
- Error: <rect> attribute width: Expected length, "NaN".
- Error: <rect> attribute height: Expected length, "NaN".
- Error: <rect> attribute x: Expected length, "NaN".
- Error: <rect> attribute y: Expected length, "NaN".
- Error: <rect> attribute width: Expected length, "NaN".
- Error: <rect> attribute height: Expected length, "NaN".
- Error: <rect> attribute x: Expected length, "NaN".
- Error: <rect> attribute y: Expected length, "NaN".
- Error: <rect> attribute width: Expected length, "NaN".
- Error: <rect> attribute height: Expected length, "NaN".
```
The example still loads and 'seems' to work, which is why I didn't catch it earlier, but the kabob menus do not open!

**Comment by dtaylor113** [comment]
In **pfToolbar** the [Menu Action v]  dropdown in the toolbar doesn't open.

**Comment by dtaylor113** [comment]
Other than those issues, LGTM :+1:

**Comment by dgutride** [comment]
@dtaylor113  - the highlighting of the close button is actually a change in behavior for ui-bootstrap - they now autofocus on the first input.  This can't be changed (we could only update the default styling if nobody likes this).  

As far as the other fixes for the Error: <rect> - I can't repro this in a clean repo with just my ui-bootstrap change.  It doesn't feel related to this change - should we hold up this PR for it?

**Comment by dgutride** [comment]
@dtaylor113 - the dropdown has been fixed on toolbar and the kebab on notification drawer

**Comment by dtaylor113** [comment]
Thanks Dana!  LGTM!  Did you ever see those <rect> exceptions in your environment?

**Comment by dgutride** [comment]
@dtaylor113 I haven't seen those.

**Pull request merged**
