### PR TITLE
Update for patternfly 2.0.0

### PR DESCRIPTION
**Pull request by erundle**
Updating angular patternfly to work with patternfly 2.0.

This updating ngDocs css includes and script includes since the patternfly 2.0 release was a breaking release.

### CODE REVIEW

**Comment by erundle** [comment]
The only thing that changed in the grunt file is the following lines which are the changes to get angular patternfly to work with patternfly 2.0:

scripts: ['lib/patternfly/components/jquery/dist/jquery.js',
+            'lib/patternfly/components/bootstrap/dist/js/bootstrap.js',
+            'lib/patternfly/components/bootstrap-combobox/js/bootstrap-combobox.js',
+            'lib/patternfly/components/bootstrap-datepicker/dist/js/bootstrap-datepicker.js',
+            'lib/patternfly/components/bootstrap-select/js/bootstrap-select.js',
+            'lib/patternfly/components/bootstrap-treeview/src/js/bootstrap-treeview.js',
+            'lib/patternfly/components/c3/c3.js',
+            'lib/patternfly/components/d3/d3.js',
+            'angular.js',
+            'dist/angular-patternfly.js',
+            'lib/patternfly/dist/js/patternfly.js'],
+          html5Mode: false,
+          styles: ['lib/patternfly/dist/css/patternfly.css', 'lib/patternfly/dist/css/patternfly-additions.css', 'misc/bootstrap-overrides.css']

**Comment by waldenraines** [comment]
I'm confused, I still see the addition of the date picker in these commits.

**Comment by kenfinnigan** [comment]
Yes, it looks like there's some remnants of date picker in the commits.

I'd also prefer if the formatting of Gruntfile.js could be fixed so that the actual changes can be seen line by line

**Comment by erundle** [comment]
If you look at the files changed the date picker is no longer there. https://github.com/patternfly/angular-patternfly/pull/23/files

Yes I created a branch of my previous commit and then rebased to remove the datepicker specific code but so I did not lose anything. 

As for the grunt file formatting. I took a copy directly from GIT again and only changed those lines listed and saved however for some reason it is picking it up as an entire change which it is not.

**Pull request closed without merging**
