### PR TITLE
Added Travis deploy config for OpenShift hot deploy.

### PR DESCRIPTION
**Pull request by dlabrecq**
Added OpenShift directory structure for hot deploy.
Modified publish.sh to also run when tags are created.
Modified travis.yml to deploy to OpenShift.

### CODE REVIEW

**Comment by dlabrecq** [comment]
@dtaylor113 @priley86 please review/merge. 

FYI, the Jenkins build has been removed in order to enable hot deploy. Travis will only push builds to OpenShift when angular-patternfly is tagged.

**Comment by dtaylor113** [comment]
LGTM

**Comment by dlabrecq** [comment]
Need one more set of eyes here. @priley86?

**Comment by priley86** [comment]
@dlabrecq looks good to me Dan, good job turning this around so fast.

**Pull request merged**
