### PR TITLE
PTNFLY-1168 Code for controls should not be in angular ngdoc snippets

### PR DESCRIPTION
**Pull request by dlabrecq**
Control code replaced with straight HTML showing each chart variation

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
The trends charts inline layout has x & y axis, it should not. I assume this is done to show one of the charts with them but without labels it's not something we should promote.

**Comment by jeff-phillips-18** [comment]
The sparkline charts for Percentage Tooltip shows x & y axis and should not for the same reasons.

**Comment by jeff-phillips-18** [comment]
Ditto for Utilization Bar chart for No Donut Center Label

**Comment by jeff-phillips-18** [comment]
Shouldn't we also remove controls from the pfC3Chart and pfHeatMap pages?

**Comment by jeff-phillips-18** [comment]
Is this limited to chart or should we also include:

pfInlineNotification
pfNotificationList
pfCardView
pfListView

**Comment by dtaylor113** [comment]
Hi, sorry I didn't do a great job of identifying all the angular-patternfly ngdocs which need to be updated, tried to do it quick during the grooming meeting.

Please update the JIRA story below with all the directives we decide to update:
https://patternfly.atlassian.net/browse/PTNFLY-1168

Thanks,
- Dave

**Comment by dtaylor113** [comment]
Downloaded repo, viewed the changed ngdocs so far.
Actually like the new layout for pfSparklineChart, nice to clearly see the different tooltip variations.

**Comment by dtaylor113** [comment]
For pfTrendsChart, the Inline example has the x and y axis turned on.  If this is intentional, then perhaps update the title to something like "Inline Layout with X & Y axis shown"

**Comment by dtaylor113** [comment]
Hi, how do we feel about adding HRs to some of the ngdocs:

**pfTrendsChart**

image

**Comment by dlabrecq** [comment]
I like that better considering there are so many examples. I thought 
about doing that, but didn't because pfUtilizationBarChart didn't have it.

**Comment by dlabrecq** [comment]
I thought we wanted an example with the x and y axis because the 
previous controls had a way to toggle this on/off. I'm planning to 
remove it per Jeff's earlier recommendation.

**Comment by jeff-phillips-18** [comment]
I would remove the axis unless we want to add labels as well but then I would add an additional large layout chart with the axes since only that layout really supports them well.

**Comment by dlabrecq** [comment]
Question about pfCardView. This page doesn't appear to have controls, like the others. It has areas for footer and filters. Each config has its own callback, which shows an alert popup. Should I remove the callbacks? As a developer, it seems like something I'd be interested in seeing here.

**Comment by dlabrecq** [comment]
Question about pfNotification. Not sure what to do here as the notifications eventually disappear? It's possible that the notifications won't be visible by the time a user scrolls to the bottom of the page. Kind of need the control to generate more.

**Comment by dlabrecq** [comment]
Question about pfList. Do we want to keep the events?

**Comment by jeff-phillips-18** [comment]
I would leave the events and such as they show good examples. 

For the notifications, IMO pfInlineNotification should show all the variations with no controls, leave pfNotificationList and Notification as is.

**Pull request closed without merging**
