### PR TITLE
Revert "chore(API docs): update header of angular-patternfly API Docs site"

### LINKED ISSUE #607: Drawer title appears to have fallen behind the accordion
I suspect with the latest changes to upstream [patternfly drawer](https://github.com/patternfly/patternfly/pull/717) updates.

screen shot 2017-09-01 at 2 38 03 pm

I've pulled master & `npm install && bower install` 2x, don't think it is local.

@jeff-phillips-18 @matthewcarleton

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Reverts patternfly/angular-patternfly#556

Related to #607 

Fixes #607

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
@dabeng I am reverting this because it messes up the styling of the components in the examples. The CSS is lengthy (I assume it comes from a less file somewhere) and uses '.showcase h3' and other such things. That selector is far too broad and should be limited only to the header (ie. .showcase > header h3).

**Comment by dtaylor113** [comment]
Does commit msg need to start with "chore(....)"

**Comment by jeff-phillips-18** [comment]
Updated the commit wording

**Comment by dabeng** [comment]
@jeff-phillips-18 , could you tell me which the components showcase.css messes up?

**Comment by jeff-phillips-18** [comment]
@dabeng I would have to reload it to find out. I know there are H3's and such that are affected. The gist of it is the .showcase selectors are broad and should be limited to the header, footer, etc.

**Pull request merged**
