### PR TITLE
Improving homepage

### PR DESCRIPTION
**Pull request by erundle**

### CODE REVIEW

**Comment by dtaylor113** [comment]
LGTM

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by waldenraines** [comment]
@erundle this looks great, thanks!

**Comment by dtaylor113** [comment]
Hi, noticed the api usage example seems to be a numbered list, was it always?

1. <ANY pf-sparkline-chart
2.     config="{object}"
3.     chart-data="{object}"
4.     [chart-height="{int}"]
5.     [show-x-axis="{boolean}"]
6.     [show-y-axis="{boolean}"]>
7.   ...
8. </ANY>

**Pull request merged**
