### PR TITLE
Update directives to align with PatternFly documentation terminology

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
IMPORTANT: This change is not backwards compatible.

The following name changes are made:

pf-utilization-chart to pf-utlization-trend-chart
pf-simple-filter to pf-filter
pf-simple-filter-results to pf-filter-results
pf-notification to pf-inline-notification
pf-simple-sort to pf-sort
pf-data-list to pf-list-view
pf-data-tiles to pf-card-view

CSS selectors have also been changed from pf-<xxx> to <xxx>-pf to be
more inline with PatternFly conventions.

### CODE REVIEW

**Comment by dtaylor113** [comment]
Hi, in pfToolbar, I can't seem to filter on age?

**Comment by dtaylor113** [comment]
Other than that one issue, LGTM

**Comment by dtaylor113** [comment]
Also, pfFilter ngdoc demo doesn't show any controls, just results list

**Comment by dtaylor113** [comment]
No demo for pfFilterFields or pfFilterResults?

**Comment by jeff-phillips-18** [comment]
No, we don't have demos for pfFilterFields or pfFilterResults, they are shown in the demo of pfToolbar

**Comment by jeff-phillips-18** [comment]
Fixed toolbar and filter demo issues.

**Comment by dtaylor113** [comment]
Ok, LGTM

**Pull request merged**
