### PR TITLE
Add pfNotificationDrawer directive

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
@dtaylor113 @dlabrecq  Please review

### CODE REVIEW

**Comment by dtaylor113** [comment]
Downloaded and built this branch.  
In the ngdoc, the description of the following parameters just end in "via".  Is this truncated?

headingInclude	
Include src for the heading area for each notification group, access the group via

subheadingInclude	
Include src for the sub-heading area for each notification group, access the group via

notificationBodyInclude	
Include src for the notification body for each notification, access the group via

**Comment by dtaylor113** [comment]
Just a minor nit, could you add text in the Demo section explaining that one should click on the bell icon to launch the notification draw.  Initially thought the demo was broken cause it's so sparse.

**Comment by dtaylor113** [comment]
Happens erratically, but after a series of opening and closing the draw, and expanding and collapsing notification groups, eventually ALL sections shrink to one line:

screenshot from 2016-06-02 10-35-48

**Comment by dtaylor113** [comment]
For the "Mark All Read" actionButtonCB function, it would be cool if it did go through all the notifications and change the unread property to false.

**Comment by dtaylor113** [comment]
When I hover over a notification group header to collapse/expand, shouldn't the cursor be a hand pointer?

**Comment by dtaylor113** [comment]
Param: 'action-button-callback' is missing from Parameters section

**Comment by jeff-phillips-18** [comment]
Thanks @dtaylor113 , I have addressed all the issues. Please re-review.

**Comment by dtaylor113** [comment]
Ok, LGTM

**Comment by dlabrecq** [comment]
LGTM

**Pull request merged**
