### PR TITLE
fix(pfFixedAccordion): Fix styling for the fixedAccordion (#634)

### LINKED ISSUE #627: Accordions do not have correct styling
Incorrect colors and collapsed indicator always shows as if open

Angular PF Fixed Accordion: 
image

PF Fixed Accordion:
image

### PR DESCRIPTION
**Pull request by cliffpyles**
## Description
Fix styling for the fixedAccordion documentation demo

Fixes #627

### CODE REVIEW

**Comment by amarie401** [comment]
Is this referencing issue #627? Also should this be a fix if so?

**Comment by amarie401** [comment]
Is this referencing issue #627?

**Comment by cliffpyles** [comment]
It is for #627. I just realized I've got one more adjustment though.

**Comment by jeff-phillips-18** [comment]
Since this is a non-distributed change, please update #627 with the information necessary to fix the issue on the application's end and close if all the problems are addressed.

**Comment by jeff-phillips-18** [comment]
@cliffpyles Looks like the issue is with https://github.com/patternfly/angular-patternfly/blob/master/styles/misc.less#L4

accordion has been renamed to uib-accordion. We should probably set it for both.

**Comment by cliffpyles** [comment]
image

**Comment by cliffpyles** [comment]
Thanks @jeff-phillips-18. I've updated the styles.

**Comment by amarie401** [comment]
LGTM

**Pull request merged**
