### PR TITLE
Adding API deployment link to README

### PR DESCRIPTION
**Pull request by erundle**

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by waldenraines** [comment]
LGTM, although we may want to add something to the API landing page (http://angular-patternfly.rhcloud.com/#/api), probably outside of this PR, as it's currently blank.

**Comment by jeff-phillips-18** [comment]
@waldenraines  Added issue #98

**Comment by erundle** [comment]
@jeff-phillips-18 the code is currently failing grunt build due to issues with the data-list indentation. Can you please address that in another commit.

**Comment by jeff-phillips-18** [comment]
It has been addressed by #95 which is awaiting merge

**Pull request merged**
