### PR TITLE
change use of patternfly setting functions from '$()' to 'patternfly'

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
to help with non-jquery applications

@dtaylor113 @dgutride @bleathem

### CODE REVIEW

**Comment by bleathem** [comment]
Should we consider passing the `patternfly` global as an argument to the IFFE?  As in:
```
(function(patternfly) {
  ...
  ...
  ...
})(patternfly)
```

**Comment by jeff-phillips-18** [comment]
@bleathem  Not all are in IIFE's, I could do it for both that are if you like, or  I could put the other in IIFEs as well. Preference?

**Comment by bleathem** [comment]
I suggest doing it for those that are in IFFEs.  If other IFFEs don't have it, we can address that in future PRs.

**Comment by jeff-phillips-18** [comment]
I will do it for all so as not to forget using 'patternfly' for these in the future.

**Pull request merged**
