### PR TITLE
Fix for #103 - pfCard directive should not show heading area if no t…

### PR DESCRIPTION
**Pull request by dtaylor113**
…itle is given

### CODE REVIEW

**Comment by waldenraines** [comment]
Should we add a test for this new function?

**Comment by dtaylor113** [comment]
Added unit test for new function.

**Comment by waldenraines** [comment]
LGTM

**Comment by waldenraines** [comment]
I'll go ahead and merge since this is isolated and straightforward.

**Comment by dtaylor113** [comment]
Thank you!

On Mon, Sep 28, 2015 at 2:31 PM, Walden Raines <notifications@github.com>
wrote:

> Merged #106 <https://github.com/patternfly/angular-patternfly/pull/106>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/patternfly/angular-patternfly/pull/106#event-421074654>
> .
>



-- 
Dave Taylor
Principle Software Engineer
(978) 392 - 1016

**Pull request merged**
