### PR TITLE
Trend chart new 'compact' and 'inline' layouts

### PR DESCRIPTION
**Pull request by dtaylor113**
Compact Layout:

image

Flat Layout:

image

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by waldenraines** [comment]
Selecting "actual" doesn't seem to work for me, I always see percentage:

screen shot 2015-09-16 at 3 21 29 pm

**Comment by waldenraines** [comment]
Is the layout name "flat" open to changes?  I don't see what is flat about this layout.  Maybe "inline"?

**Comment by dtaylor113** [comment]
@erundle please merge this when/if you are happy with it.
Thanks,
 - Dave

**Comment by waldenraines** [comment]
> Actual .vs Percent currently only work for 'large', 'small', and 'compact' layouts. Currently, 'percentage' format is the only one officially approved for the 'flat' layout, but this may change in the future.

Then we should disabled this option when flat is selected.  Otherwise it is quite confusing.

**Comment by dtaylor113** [comment]
Ok, Actual .vs Percent is hidden when layout === 'inline'.
Please merge if happy with this PR.
Thanks,
- Dave

**Pull request merged**
