### PR TITLE
fix(pfFilterPanel): make filter panel background semi-transparent

### PR DESCRIPTION
**Pull request by dtaylor113**
## Description
Make the filter panel background semi-transparent to see content under the panel.

Before:
image

After:
image

Related Issue: https://github.com/openshift/origin-web-catalog/issues/536

## PR Checklist

- [X] Screenshots are attached (if there are visual changes in the UI)
- [X] A Designer (@beanh66) is assigned as a reviewer (if there are visual changes in the UI)
- [X] A CSS rep (@cshinn) is assigned as a reviewer (if there are visual changes in the UI)

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
@beanh66 Is there an issue filed to update this in the design pattern at http://www.patternfly.org/pattern-library/forms-and-controls/filter/#/design

**Comment by beanh66** [comment]
Thanks @jeff-phillips-18 I will create an issue for that update in PF design.

**Comment by jeff-phillips-18** [comment]
@dtaylor113 Could you update to patternfly 3.36.0 or greater to see if that fixes the Node Security check failure?

**Comment by dtaylor113** [comment]
> @dtaylor113 Could you update to patternfly 3.36.0 or greater to see if that fixes the Node Security check failure?

Upgraded to patternfly 3.36.0, that seemed to fix the Node Security issue.

**Pull request merged**
