### PR TITLE
Update build such that dist/docs is not updated every time

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
This will require that when a release is done, the grunt task ngdocs:publish is run and the doc changes are pushed at that point.

### CODE REVIEW

**Comment by dlabrecq** [comment]
LGTM. Much cleaner code reviews

**Comment by dtaylor113** [comment]
So I downloaded this repo/branch and ran 'grunt build' who's 'grunt clean:all' deletes the 'dist/docs' dir, so now my unstaged git changes shows all the missing 'dist/docs' dir.
Think we need to replace the 'clean:all' with more target dist cleans, leave the dist/docs as is until 'grunt ngdocs:publish' updates 'dist/docs'.

**Comment by dtaylor113** [comment]
This seemed to do it:

clean: {
...
...
        all: ['dist/*', '!dist/docs']
      },

**Comment by dtaylor113** [comment]
Might want to add a 'clean:distdocs' to the ngdocs:publish task so that we start with a clean dist/docs dir before copying in all files from 'docs'.

**Comment by jeff-phillips-18** [comment]
@dtaylor113 I have addressed both concerns

**Comment by dtaylor113** [comment]
LGTM

**Pull request merged**
