### PR TITLE
Updated Travis to use Node 4

### PR DESCRIPTION
**Pull request by dlabrecq**
The goal of this PR is to satisfy requirements of PTNFLY-1866, and ensure Angular P.F. builds properly with Node 4 LTS.

### CODE REVIEW

**Comment by dlabrecq** [comment]
@bleathem @priley86 Please review/merge? I would like to have this in place prior to starting the release.

**Comment by priley86** [comment]
@dlabrecq looks good - npm installed and ran grunt build just fine with node 4. let's upgrade npm later like we discussed...

**Comment by bleathem** [comment]
Awesome!  Will merge.

**Comment by dlabrecq** [comment]
Thanks, guys!

**Pull request merged**
