### PR TITLE
Pf vertical navigation ui sref support

### PR DESCRIPTION
**Pull request by lorthirk**
Implements #342. Credits to @MattiaDalBen for the unit tests and the help for the optional service injection.

### CODE REVIEW

**Comment by dtaylor113** [comment]
LGTM.  cloned this branch.  all unit tests passed and ngdocs Navigation example works fine with these changes.
@lorthirk It would be great if you could update the [pf-vert-nav ngdoc](https://github.com/patternfly/angular-patternfly/blob/master/src/navigation/vertical-navigation-directive.js) example to indicate support for angular-ui-router.  Please include any setup or usage examples required to use pf-vert-nav and angular-ui-router.  -thanks!

**Comment by lorthirk** [comment]
@MattiaDalBen it would be great if you could cover this tomorrow

**Comment by MattiaDalBen** [comment]
@lorthirk I'm on it!

**Comment by MattiaDalBen** [comment]
@dtaylor113  as requested I updated the pf-vert-nav ngdoc example.

**Comment by dtaylor113** [comment]
Hi @MattiaDalBen, thanks it looks great.  One small nit, could you please add an initial topic sentence to the beginning of the 'pfVerticalNavigation - Router' ngdoc example so that it differentiates itself from the 'Basic' example.  Something like: "This example shows how to use pfVerticalNavigation with angular-ui-router's $states and uiSrefs."   -thanks!

**Comment by MattiaDalBen** [comment]
@dtaylor113 Updated description.

**Comment by dtaylor113** [comment]
LGTM!  Thanks

**Pull request merged**
