### PR TITLE
Added a script used to help create and test apf releases

### PR DESCRIPTION
**Pull request by dlabrecq**
This script will bump the version number for the Angular PatternFly repo.

sh [-x] release.sh [-h|f] -v <version>

Example: sh release.sh -v 3.7.0 -f

OPTIONS:
h       Display this message (default) 
f       Force push to new repo branch (e.g., bump-v3.7.0)
v       The version number (e.g., 3.7.0)

### CODE REVIEW

**Comment by dlabrecq** [comment]
@dtaylor113 @jeff-phillips-18 @bleathem please review.

**Comment by bleathem** [comment]
Seems very comprehensive, let's merge.

+1

**Comment by bleathem** [comment]
Like the other accompanying build script PRs this looks great.

+1

**Comment by jeff-phillips-18** [comment]
LGTM

**Pull request merged**
