### PR TITLE
Split pfCard examples to be included separately in patternfly-toolkit.

### PR DESCRIPTION
**Pull request by dlabrecq**
@dtaylor113 and @jeff-phillips-18 please review.

### CODE REVIEW

**Comment by dtaylor113** [comment]
LGTM:  I would just suggest making the titles be:

pfCard: Timeframe Filters
pfCard: Trend Charts
pfCard: Multiple Utilization Bars

Either a colon ":" or perhaps a dahs "-".  -thanks

**Comment by dlabrecq** [comment]
I can't do the colon ":", but dash "-" works fine. When colon is added, the "pfCard:" prefix isn't shown.

**Comment by dtaylor113** [comment]
ok, sounds good

**Comment by jeff-phillips-18** [comment]
Did you think about putting the examples in a different location from the actual directives? This would have less clutter in the actual code directories and make the examples easily distinguished from additional directives.

**Comment by dlabrecq** [comment]
I actually tried placing examples under the doc name "patternfly.examples". In this scenario, the directive only contained one example (i.e., utilization), while "pfCard Trend" and "pfCard Timeframe" were split out. 

The new examples appeared as a block, somewhere in the middle of everything else. My thinking was it may be best to keep all the pfCard examples together? It could be confusing jumping around in order to find all examples? 

I can throw an example together if you would like to review that, first?

**Comment by dlabrecq** [comment]
I created an alternate example #221 with pfCard examples under the "patternfly.examples" doc name. Please take a look and let me know what you think?

**Comment by dtaylor113** [comment]
I think Jeff was just talking about moving the actual files to an 'examples' directory -leaving the ngdoc @names the same.   Just concerned about cluttering up the number of files in the actual directive directories

**Comment by dlabrecq** [comment]
Ok, that's easy enough.

**Comment by jeff-phillips-18** [comment]
@dtaylor113 exactly. The concern is more about cluttering the directory and not being clear which files contain examples vs the actual directives.

**Comment by dlabrecq** [comment]
@jeff-phillips-18, I've moved the new files to their own examples directory.

**Comment by dtaylor113** [comment]
LGTM

**Comment by jeff-phillips-18** [comment]
LGTM

**Pull request merged**
