### PR TITLE
Updated 4.0-dev to PatternFly 3.25.0 and jQuery 3

### PR DESCRIPTION
**Pull request by bleathem**
Updated to PatternFly 3.25.0.
Corrected jQuery 3 errors.

### CODE REVIEW

**Comment by bleathem** [comment]
I ran through all the API docs with the jquery migrate plugin active.  I corrected all errors, however we still have the following warning for the CanvasEditor:
http://0.0.0.0:8000/#/api/patternfly.canvas.directive:pfCanvasEditor
```
JQMIGRATE: jQuery.unique is deprecated, use jQuery.uniqueSort
migrateWarn	@	jquery-migrate-3.0.0.js:62
get	@	jquery-migrate-3.0.0.js:75
i	@	jquery-ui.min.js:6
_classes	@	jquery-ui.min.js:6
_toggleClass	@	jquery-ui.min.js:6
_addClass	@	jquery-ui.min.js:6
_create	@	jquery-ui.min.js:11
(anonymous)	@	jquery-ui.min.js:6
_createWidget	@	jquery-ui.min.js:6
t.(anonymous function).(anonymous function)	@	jquery-ui.min.js:6
(anonymous)	@	jquery-ui.min.js:6
each	@	jquery.js:362
each	@	jquery.js:157
t.fn.(anonymous function)	@	jquery-ui.min.js:6
updateDroppable	@	angular-dragdrop.js:395
link	@	angular-dragdrop.js:405
(anonymous)	@	angular.js:1259
invokeLinkFn	@	angular.js:10152
nodeLinkFn	@	angular.js:9551
compositeLinkFn	@	angular.js:8810
compositeLinkFn	@	angular.js:8813
compositeLinkFn	@	angular.js:8813
nodeLinkFn	@	angular.js:9545
(anonymous)	@	angular.js:9886
processQueue	@	angular.js:16696
(anonymous)	@	angular.js:16712
$eval	@	angular.js:17994
$digest	@	angular.js:17808
$apply	@	angular.js:18102
bootstrapApply	@	angular.js:1812
invoke	@	angular.js:4771
doBootstrap	@	angular.js:1810
bootstrap	@	angular.js:1830
link	@	angular-bootstrap-prettify.js:263
(anonymous)	@	angular.js:1259
invokeLinkFn	@	angular.js:10152
nodeLinkFn	@	angular.js:9551
compositeLinkFn	@	angular.js:8810
compositeLinkFn	@	angular.js:8813
compositeLinkFn	@	angular.js:8813
compositeLinkFn	@	angular.js:8813
publicLinkFn	@	angular.js:8690
link	@	angular.js:27442
(anonymous)	@	angular.js:1259
invokeLinkFn	@	angular.js:10152
nodeLinkFn	@	angular.js:9551
compositeLinkFn	@	angular.js:8810
publicLinkFn	@	angular.js:8690
lazyCompilation	@	angular.js:9047
boundTranscludeFn	@	angular.js:8827
controllersBoundTransclude	@	angular.js:9601
(anonymous)	@	angular.js:27388
processQueue	@	angular.js:16696
(anonymous)	@	angular.js:16712
$eval	@	angular.js:17994
$digest	@	angular.js:17808
$apply	@	angular.js:18102
done	@	angular.js:12082
completeRequest	@	angular.js:12291
requestLoaded	@	angular.js:12219
XMLHttpRequest.send (async)		
(anonymous)	@	angular.js:12265
sendReq	@	angular.js:12027
serverRequest	@	angular.js:11822
processQueue	@	angular.js:16696
(anonymous)	@	angular.js:16712
$eval	@	angular.js:17994
$digest	@	angular.js:17808
$apply	@	angular.js:18102
bootstrapApply	@	angular.js:1812
invoke	@	angular.js:4771
doBootstrap	@	angular.js:1810
bootstrap	@	angular.js:1830
angularInit	@	angular.js:1715
(anonymous)	@	angular.js:32616
mightThrow	@	jquery.js:3583
process	@	jquery.js:3651
setTimeout (async)		
(anonymous)	@	jquery.js:3689
fire	@	jquery.js:3317
fireWith	@	jquery.js:3447
fire	@	jquery.js:3455
fire	@	jquery.js:3317
fireWith	@	jquery.js:3447
ready	@	jquery.js:3920
completed	@	jquery.js:3930
```
Which originates from the jquery.ui library.

**Comment by bleathem** [comment]
I also hit on this migrate plugin bug a number of times, but I think we can ignore it:
https://github.com/angular-ui/ui-select/issues/1790

**Comment by dtaylor113** [comment]
> have the following warning for the CanvasEditor

Looked through the pfCanvasEditor code, do not see use of the 'unique' API.

**Comment by dtaylor113** [comment]
LGTM!  -Thanks

**Pull request merged**
