### PR TITLE
Angular Bootstrap Switch added as a dependency

### PR DESCRIPTION
**Pull request by romanblanco**
@jeff-phillips-18

### CODE REVIEW

**Comment by dlabrecq** [comment]
LGTM

**Comment by jeff-phillips-18** [comment]
Why do we need to add this dependency?

**Comment by romanblanco** [comment]
[Bootstrap switch](http://www.bootstrap-switch.org/) itself seems to not working with AngularJS, at least to me.

**Comment by jeff-phillips-18** [comment]
But unless angular-patternfly depends on it then we shouldn't add the dependency. If we had a component built on top of it then it would make sense. Projects using angular and the bootstrap switch can add the dependency.

**Comment by romanblanco** [comment]
@jeff-phillips-18 thanks, closing this issue

**Pull request closed without merging**
