### PR TITLE
Update utilization chart available value when used or total changes

### PR DESCRIPTION
**Pull request by erundle**
This has already been merged into master. Adding to 2.3.x so that we can create a patch release

@spadgett

### CODE REVIEW

**Comment by spadgett** [comment]
Hi, @erundle. It looks like your commit is different from #143. The change needs to be in utilization-chart-directive.js.

**Comment by erundle** [comment]
@spadgett what is different about it?

**Comment by spadgett** [comment]
The change is not in the correct file. It should be in utilization-chart-directive.js, not donut-pct-chart-directive.js.

**Comment by erundle** [comment]
@spadgett nevermind it looks like we have the bug in two places and show be applied to both files

**Pull request merged**
