### PR TITLE
Webpack notes on README.md

### PR DESCRIPTION
**Pull request by lorthirk**
As @bleathem asked, I wrote down a couple of usage notes about using Angular-Patternfly with Webpack. Please note that these notes are coming from my personal experience, and being a newbie with Webpack, I cannot guarantee that they follow any best practice; of course, any suggestion about these or other notes are more than welcome.

On a side note: one of the two notes (the one about 3.14.0) is more about Patternfly itself than Angular-Patternfly. Should I replicate that one in the Patternfly README.md as well?

### CODE REVIEW

**Comment by bleathem** [comment]
Thanks for the contribution @lorthirk!  This looks good to me as an initial stab at webpack documentation.  Although I don't feel the note about consuming version 3.14 should be in the README, as that release has been superseded by a new release.

**Comment by lorthirk** [comment]
Ok. I'll pull it out as soon as I get back home.

**Comment by lorthirk** [comment]
Note removed 😉

**Comment by dlabrecq** [comment]
LGTM

**Pull request merged**
