### PR TITLE
Fix to allow previous from substeps when there is no backCallback

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
(already fixed in 4.x)

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
@cdcabrera It ought to be, I will update.

**Comment by jeff-phillips-18** [comment]
@cdcabrera added the same optimization to wizard directive and next function of wizard step directive. Please re-review. Thanks!

**Comment by bleathem** [comment]
Does this PR need to be merged for the 3.24.0 release?

**Comment by jeff-phillips-18** [comment]
@bleathem yes

**Pull request merged**
