### PR TITLE
Add capability to add app defined action buttons to the toolbar

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Currently, there is a limitation in the toolbar. One cannot add, say, a
dropdown button to the action buttons. This provides the capability for
an application to add buttons how they want to the toolbar action
buttons area.

### CODE REVIEW

**Comment by dtaylor113** [comment]
ngDocs needs to be updated with this new config option.

**Comment by dtaylor113** [comment]
The primary and more actions have a 'actionFn' callback.  Just curious, how would someone define a callback for included actions?

**Comment by jeff-phillips-18** [comment]
The application can add ng-click or whatever they want to their HTML. This is a mechanism for the application to provide buttons however they would like to the button area of the toolbar.

**Comment by jeff-phillips-18** [comment]
Added ngdoc

**Comment by dtaylor113** [comment]
Ok, perhaps it would be good to have an example of ng-click and ng-change for the dropdown list.  Just to show how to do that with included actions since it is different from how the other action buttons are handled.

**Pull request closed without merging**
