### PR TITLE
Add Fixed Accordion Utility

### PR DESCRIPTION
**Pull request by jeff-phillips-18**

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
@dtaylor113 @dlabrecq Please review

**Comment by dtaylor113** [comment]
Not sure why 'pfFixedAccordion' is in 'patternfly.utils', seems like it should be in just 'patternfly'.
'patternfly' currently has the following directives: pfSelect, pfFocused, pfValidation; seems like pfFixedAccordion would fit here.

**Comment by jeff-phillips-18** [comment]
I've modified it to show up in the base patternfly area of ngDocs.

**Comment by dlabrecq** [comment]
LGTM

**Pull request merged**
