### PR TITLE
Adding ui-bootstrap 0.13.x to the project

### PR DESCRIPTION
**Pull request by erundle**
Without making these changes you can't inject ui.bootstrap into any module. You get conflicts with angular-bootstrap-prettify.js

### CODE REVIEW

**Comment by waldenraines** [comment]
@erundle what is `angular-bootstrap-prettify.js` for, why is it needed, and why can't it be included via bower?

**Comment by erundle** [comment]
It is code highlighting similar to google code prettifier (ngDocs is already using this) but I needed to add it to our project directly and comment out an offending line. See line 208

**Comment by dtaylor113** [comment]
LGTM

**Comment by jeff-phillips-18** [comment]
LGTM

**Comment by waldenraines** [comment]
@erundle can you file an issue to remove angular-bootstrap-prettify.js from source control once https://github.com/angular-ui/bootstrap/issues/4315 is resolved so we don't forget?  

Otherwise LGTM.

**Comment by erundle** [comment]
Issue created: https://github.com/patternfly/angular-patternfly/issues/109

**Comment by waldenraines** [comment]
@erundle thanks!

**Pull request merged**
