### PR TITLE
Fix for heat map tooltips with angular ui bootstrap upgrade

### PR DESCRIPTION
**Pull request by jeff-phillips-18**

### CODE REVIEW

**Comment by dtaylor113** [comment]
Ah..here it is :-)  I think this branch is missing #360  LGTM

**Comment by jeff-phillips-18** [comment]
I put the changes from #360 in with #361. In hind-sight, I ought not to have done that 😊

**Comment by dtaylor113** [comment]
Ok, no prob :-)

**Comment by dlabrecq** [comment]
LGTM

**Pull request merged**
