### PR TITLE
Build Package Updated

### PR DESCRIPTION
**Pull request by cdcabrera**
Extension of PR #459 & #464 NPM & ReadMe Updates

Changes:
- ReadMe
  - NPM script updates
  - Unit testing 
- NPM
  - Script aliases for Grunt tasks
  - NPM Ignore for cleaner install
- Bower 
  - JSON ignore, for cleaner install
- Grunt
  - Less copy as part of the ```dist```/distribution

### CODE REVIEW

**Comment by dtaylor113** [comment]
Hi, does this change the contents of the /dist directory?

**Comment by cdcabrera** [comment]
@dtaylor113  it does, it should produce something like...

for Node Modules....
screen shot 2017-06-01 at 10 11 11 am




and Bower Components...
screen shot 2017-06-01 at 10 10 38 am

**Comment by dtaylor113** [comment]
What I'm getting at is we should document any changes to the '/dist' contents (files removed, name changes, etc) so that when users update to the next version, they understand what they may have to change in their app to consume the new a-pf version.  -thanks!

**Comment by cdcabrera** [comment]
Sure thing, we can do a compare/contrast. You thinking on the [Change Log Md](https://github.com/patternfly/angular-patternfly/blob/master/CHANGELOG.md) or the ReadMe?

**Comment by cdcabrera** [comment]
Changelog.md removed in favor of release notes

**Comment by cdcabrera** [comment]
# Dist/Distribution Clean Up
The ```dist``` or distribution output for Angular PatternFly has been updated for both Bower and NPM installs.

Prior versions of Angular PatternFly included multiple repository directories that were geared towards the build. The following directories and subsequent files are no longer included as part of the install
- .openshift
- misc
- dist/docs
- scripts
- src
- styles
- test

If your project was consuming the ```Less``` files contained either under the original ```styles``` directory, or under the ```src/[COMPONENT NAME]```, those files are now located under ```dist/less```, your reference paths will need to be updated.

The ```dist``` directory now includes a ```dist/less```...
- dist/imgs
- dist/less ***NEW***
  - *.less
  - dependencies
    - *.less
- dist/styles
  - angular-patternfly.css
  - angular-patternfly.min.css
- angular-patternfly.js
- angular-patternfly.min.js

# Noteworthy changes
- Grunt tasks have been aliased through NPM scripts.

**Comment by dtaylor113** [comment]
Hi @cdcabrera, great comments!  You could probably create a draft Release Notes for v4.0.1 and include these comments. -thanks

**Comment by cdcabrera** [comment]
can do on the draft Release Notes

**Pull request merged**
